service: burritobot

provider:
  name: aws
  runtime: go1.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource:
        - "arn:aws:dynamodb:us-east-1:288184449763:table/burritobot_user_stats"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  event_listener:
    handler: bin/event_listener
    events:
      - http:
          path: event_listener
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
